name: CI/CD to Azure Container Apps

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build & deploy to Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: .
          acrName: melonopsmainregistry
          containerAppName: melonops-backend
          resourceGroup: melonops
      - name: Apply missing env vars via CLI
        run: |
          az containerapp update \
            --name melonops-backend \
            --resource-group melonops \
            --set-env-vars \
              DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" \
              GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" \
              GOOGLE_API_KEY="${{ secrets.GOOGLE_API_KEY }}" \
              AZURE_API_KEY="${{ secrets.AZURE_API_KEY }}" \
              AZURE_ENDPOINT="${{ secrets.AZURE_ENDPOINT }}" \
              FRONTEND_APP_URL="${{ secrets.FRONTEND_APP_URL }}" \
              LANGFUSE_PUBLIC_KEY="${{ secrets.LANGFUSE_PUBLIC_KEY }}"
              LANGFUSE_SECRET_KEY="${{ secrets.LANGFUSE_SECRET_KEY }}"
              LANGFUSE_HOST="${{ secrets.LANGFUSE_HOST }}"
